services:
  prometheus:
    image: confluentinc/cp-enterprise-prometheus:2.2.0
    hostname: cp-enterprise-prometheus
    container_name: prometheus
    volumes:
      - ./vol/config:/mnt/config
    ports:
      - "9090:9090"
    environment:
      CONFIG_PATH: "/mnt/config"
      SHOULD_LOG_TO_FILE: false


  alertmanager:
    image: confluentinc/cp-enterprise-alertmanager:2.2.0
    hostname: cp-enterprise-alertmanager
    container_name: alertmanager
    depends_on:
      - prometheus
    volumes:
      - ./vol/config:/mnt/config
    ports:
      - "19093:19093"
    environment:
      CONFIG_PATH: "/mnt/config"
      SHOULD_LOG_TO_FILE: false


  control-center:
    image: confluentinc/cp-enterprise-control-center-next-gen:2.2.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - prometheus
      - alertmanager
    ports:
      - "9021:9021"
    volumes:
      - ./vol/config:/mnt/config
    environment:

      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker-1:29092,broker-2:29092,broker-3:29092'

      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_CONNECT_HEALTHCHECK_ENDPOINT: '/connectors'

      CONTROL_CENTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081

      CONTROL_CENTER_REPLICATION_FACTOR: 3
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 3
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 3

      CONFLUENT_METRICS_TOPIC_REPLICATION: 3

      CONTROL_CENTER_PROMETHEUS_ENABLE: true
      CONTROL_CENTER_PROMETHEUS_URL: http://prometheus:9090
      CONTROL_CENTER_PROMETHEUS_RULES_FILE: /mnt/config/trigger_rules-generated.yml

      CONTROL_CENTER_ALERTMANAGER_URL: http://alertmanager:19093
      CONTROL_CENTER_ALERTMANAGER_CONFIG_FILE: /mnt/config/alertmanager-generated.yml

      PORT: 9021
